#  http://localhost:8081/swagger-ui/index.html#/
server:
  port: ${PORT:8081}
  application:
    name: OrderService

supabase:
  url: ${SUPABASE_URL}
  projectId: ${SUPABASE_PROJECT_ID}
  anonKey: ${SUPABASE_ANON_KEY}
  jwtSecret: ${SUPABASE_JWT_SECRET}
  successfulLoginRedirectPage: "/account"
  passwordRecoveryPage: /updatePassword
  unauthenticatedPage: /unauthenticated
  unauthorizedPage: /unauthorizedPage
  sslOnly: false
  database:
    host: ${SUPABASE_HOST}
    password: ${SUPABASE_DATABASE_PASSWORD}

spring:
  zipkin:
    base-url: ${ZIPKIN_SERVER_ADDRESS:http://zipkin:9411}
  datasource:
    url: ${SUPABASE_DATABASE_URL}
    username: ${SUPABASE_DATABASE_USER}
    password: ${SUPABASE_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0